-- SOMA, SUBTRAÇÃO, MULTIPLICAÇÃO E DIVISÃO

SELECT 
	5 + 2 AS SOMA,
	5 - 2 AS SUBTRACAO,
	5 * 2 AS MULTIPLICAO,
	5 / 2 AS DIVISAO

-- FUNÇÕES MATEMATICA EXPONECIAÇÃO.

SELECT
	SQUARE(5) AS Quadrado,
	POWER(5, 3) AS POTENCIA

-- VALOR ABSOLUTO

SELECT ABS(-100) AS VALOR_ABSOLUTO

-- RAIZ QUADRADA 
	SELECT SQRT(5) AS RESULTADO
-- PI
	SELECT PI() AS RESULTADO